### ISSUE TITLE
Precision from float value with 4 digits?

### ISSUE THREAD

**Issue by Alifar** [ArthurGuibert/FSLineChart#39]
Hi there,

First of all, thank you for this great library. 

I got a question about the precision of the float, when I set the CGFloat value to .4f it doesn't return the last 2 digits as seen on the screenshot, this results in 0.

Also the chart is showing almost a straight line because it doesn't measure the last 2 digits while the last two digits are very important.

```
self.lineChart.labelForValue = ^(CGFloat value) {
return [NSString stringWithFormat:@"€ %.4f", value];
};
```

<img width="369" alt="schermafbeelding 2016-10-28 om 17 09 47" src="https://cloud.githubusercontent.com/assets/6464812/19812190/d6875376-9d34-11e6-90cb-e4e4b601aa6b.png">

**Comment by ArthurGuibert** [comment]
Hi Alifar,

The precision here is not the issue but the scale. You can see my answer to a very similar issue here: https://github.com/ArthurGuibert/FSLineChart/issues/35

The idea is not to start from 0 but from 0.04 for example so that you can see the variation more easily in your chart.

However it seems to be quite a common request so maybe I should add a method to optimize the scale. For example by calculating the minimum value and then offset the whole chart automatically.

**Comment by Alifar** [comment]
How can I start with 0.04? Where do I need to set this up? Thanks.

**Comment by ArthurGuibert** [comment]
Just get the minimum from your data set: iterate through all your values and find the minimum.

**Comment by Alifar** [comment]
Hi there, I have those, but I ment code wise how do I need to set this up? Can you show me a snippet if possible?

Thanks again.
